root: true
extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:react/recommended
  - '@react-native-community'
  - plugin:react-native/all
  - plugin:jest/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - react
  - react-native
  - jest
  - prettier
  - import
settings:
  react:
    version: detect
rules:
  no-console: warn
  yoda: off
  '@typescript-eslint/explicit-function-return-type': off
  react-native/no-raw-text: off
  react-native/sort-styles: off
  no-void: off
